// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSBUlynRalqW8Xdx-40GfBp8UsDStzhxE',
    appId: '1:932406242298:web:f77e52c3c7e07968ba1243',
    messagingSenderId: '932406242298',
    projectId: 'sist-d464f',
    authDomain: 'sist-d464f.firebaseapp.com',
    databaseURL: 'https://sist-d464f-default-rtdb.firebaseio.com',
    storageBucket: 'sist-d464f.firebasestorage.app',
    measurementId: 'G-P43614W1CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyL0TLYm48Kp_mm0pGMPXV2LFEUc_v8ng',
    appId: '1:932406242298:android:0c584ff86808c9aaba1243',
    messagingSenderId: '932406242298',
    projectId: 'sist-d464f',
    databaseURL: 'https://sist-d464f-default-rtdb.firebaseio.com',
    storageBucket: 'sist-d464f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq-X39re5jmDrATd4J_165cn9CVEaZEPY',
    appId: '1:932406242298:ios:12628aa8fe2cc376ba1243',
    messagingSenderId: '932406242298',
    projectId: 'sist-d464f',
    databaseURL: 'https://sist-d464f-default-rtdb.firebaseio.com',
    storageBucket: 'sist-d464f.firebasestorage.app',
    iosBundleId: 'com.example.sisthub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq-X39re5jmDrATd4J_165cn9CVEaZEPY',
    appId: '1:932406242298:ios:12628aa8fe2cc376ba1243',
    messagingSenderId: '932406242298',
    projectId: 'sist-d464f',
    databaseURL: 'https://sist-d464f-default-rtdb.firebaseio.com',
    storageBucket: 'sist-d464f.firebasestorage.app',
    iosBundleId: 'com.example.sisthub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSBUlynRalqW8Xdx-40GfBp8UsDStzhxE',
    appId: '1:932406242298:web:aefc861f1f3fde79ba1243',
    messagingSenderId: '932406242298',
    projectId: 'sist-d464f',
    authDomain: 'sist-d464f.firebaseapp.com',
    databaseURL: 'https://sist-d464f-default-rtdb.firebaseio.com',
    storageBucket: 'sist-d464f.firebasestorage.app',
    measurementId: 'G-T1PHEGN1Q6',
  );
}
