name: university_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.18.0
  image_picker: ^1.0.0
  http: ^1.3.0
  video_player: ^2.8.2
  url_launcher: ^6.1.14
  web_socket_channel: ^3.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your image asset here
  assets:
    - assets/images/193-300x200.jpg
    - assets/images/default_cover.jpg

